# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_animal.ui'
#
# Created: Sat Apr 13 21:44:19 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Animal(object):
    def setupUi(self, Animal):
        Animal.setObjectName(_fromUtf8("Animal"))
        Animal.resize(1065, 835)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Animal)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(Animal)
        self.label_2.setMinimumSize(QtCore.QSize(80, 30))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.nameLineEdit = QtGui.QLineEdit(Animal)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.nameLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.nameLineEdit.setInputMask(_fromUtf8(""))
        self.nameLineEdit.setText(_fromUtf8(""))
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.horizontalLayout_2.addWidget(self.nameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(Animal)
        self.label_3.setMinimumSize(QtCore.QSize(80, 30))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.officialNamelineEdit = QtGui.QLineEdit(Animal)
        self.officialNamelineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.officialNamelineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.officialNamelineEdit.setObjectName(_fromUtf8("officialNamelineEdit"))
        self.horizontalLayout_3.addWidget(self.officialNamelineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(Animal)
        self.label_8.setMinimumSize(QtCore.QSize(80, 30))
        self.label_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.birthdayEdit = QtGui.QDateEdit(Animal)
        self.birthdayEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.birthdayEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.birthdayEdit.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.birthdayEdit.setCalendarPopup(True)
        self.birthdayEdit.setObjectName(_fromUtf8("birthdayEdit"))
        self.horizontalLayout_6.addWidget(self.birthdayEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.SpecieLayout = QtGui.QHBoxLayout()
        self.SpecieLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.SpecieLayout.setObjectName(_fromUtf8("SpecieLayout"))
        self.label_4 = QtGui.QLabel(Animal)
        self.label_4.setMinimumSize(QtCore.QSize(80, 30))
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.SpecieLayout.addWidget(self.label_4)
        self.specieComboBox = QtGui.QComboBox(Animal)
        self.specieComboBox.setObjectName(_fromUtf8("specieComboBox"))
        self.SpecieLayout.addWidget(self.specieComboBox)
        self.newSpecieButton = QtGui.QPushButton(Animal)
        self.newSpecieButton.setMinimumSize(QtCore.QSize(25, 25))
        self.newSpecieButton.setMaximumSize(QtCore.QSize(25, 25))
        self.newSpecieButton.setStatusTip(_fromUtf8(""))
        self.newSpecieButton.setWhatsThis(_fromUtf8(""))
        self.newSpecieButton.setObjectName(_fromUtf8("newSpecieButton"))
        self.SpecieLayout.addWidget(self.newSpecieButton)
        self.verticalLayout.addLayout(self.SpecieLayout)
        self.RaceLayout = QtGui.QHBoxLayout()
        self.RaceLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.RaceLayout.setObjectName(_fromUtf8("RaceLayout"))
        self.label_5 = QtGui.QLabel(Animal)
        self.label_5.setMinimumSize(QtCore.QSize(80, 30))
        self.label_5.setMaximumSize(QtCore.QSize(80, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.RaceLayout.addWidget(self.label_5)
        self.raceComboBox = QtGui.QComboBox(Animal)
        self.raceComboBox.setObjectName(_fromUtf8("raceComboBox"))
        self.RaceLayout.addWidget(self.raceComboBox)
        self.newRaceButton = QtGui.QPushButton(Animal)
        self.newRaceButton.setMinimumSize(QtCore.QSize(25, 25))
        self.newRaceButton.setMaximumSize(QtCore.QSize(25, 25))
        self.newRaceButton.setObjectName(_fromUtf8("newRaceButton"))
        self.RaceLayout.addWidget(self.newRaceButton)
        self.verticalLayout.addLayout(self.RaceLayout)
        self.sexLayout = QtGui.QHBoxLayout()
        self.sexLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.sexLayout.setObjectName(_fromUtf8("sexLayout"))
        self.label_6 = QtGui.QLabel(Animal)
        self.label_6.setMinimumSize(QtCore.QSize(80, 30))
        self.label_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.sexLayout.addWidget(self.label_6)
        self.sexComboBox = QtGui.QComboBox(Animal)
        self.sexComboBox.setObjectName(_fromUtf8("sexComboBox"))
        self.sexLayout.addWidget(self.sexComboBox)
        self.newSexButton = QtGui.QPushButton(Animal)
        self.newSexButton.setMinimumSize(QtCore.QSize(25, 25))
        self.newSexButton.setMaximumSize(QtCore.QSize(25, 25))
        self.newSexButton.setObjectName(_fromUtf8("newSexButton"))
        self.sexLayout.addWidget(self.newSexButton)
        self.verticalLayout.addLayout(self.sexLayout)
        self.colorLayout = QtGui.QHBoxLayout()
        self.colorLayout.setObjectName(_fromUtf8("colorLayout"))
        self.label_7 = QtGui.QLabel(Animal)
        self.label_7.setMinimumSize(QtCore.QSize(80, 30))
        self.label_7.setMaximumSize(QtCore.QSize(80, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.colorLayout.addWidget(self.label_7)
        self.colorComboBox = QtGui.QComboBox(Animal)
        self.colorComboBox.setObjectName(_fromUtf8("colorComboBox"))
        self.colorLayout.addWidget(self.colorComboBox)
        self.newColorButton = QtGui.QPushButton(Animal)
        self.newColorButton.setMinimumSize(QtCore.QSize(25, 25))
        self.newColorButton.setMaximumSize(QtCore.QSize(25, 25))
        self.newColorButton.setObjectName(_fromUtf8("newColorButton"))
        self.colorLayout.addWidget(self.newColorButton)
        self.verticalLayout.addLayout(self.colorLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Animal)
        self.label.setMinimumSize(QtCore.QSize(80, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.recNumlineEdit = QtGui.QLineEdit(Animal)
        self.recNumlineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.recNumlineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.recNumlineEdit.setObjectName(_fromUtf8("recNumlineEdit"))
        self.horizontalLayout.addWidget(self.recNumlineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(Animal)
        self.label_12.setMinimumSize(QtCore.QSize(80, 30))
        self.label_12.setMaximumSize(QtCore.QSize(80, 30))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.passportLineEdit = QtGui.QLineEdit(Animal)
        self.passportLineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.passportLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.passportLineEdit.setObjectName(_fromUtf8("passportLineEdit"))
        self.horizontalLayout_5.addWidget(self.passportLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(Animal)
        self.label_9.setMinimumSize(QtCore.QSize(80, 30))
        self.label_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.microLineEdit = QtGui.QLineEdit(Animal)
        self.microLineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.microLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.microLineEdit.setObjectName(_fromUtf8("microLineEdit"))
        self.horizontalLayout_4.addWidget(self.microLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_10 = QtGui.QLabel(Animal)
        self.label_10.setMinimumSize(QtCore.QSize(80, 30))
        self.label_10.setMaximumSize(QtCore.QSize(80, 30))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.tattooLineEdit = QtGui.QLineEdit(Animal)
        self.tattooLineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.tattooLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tattooLineEdit.setObjectName(_fromUtf8("tattooLineEdit"))
        self.horizontalLayout_7.addWidget(self.tattooLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.label_11 = QtGui.QLabel(Animal)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setMaximumSize(QtCore.QSize(330, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.insuranceEdit = QtGui.QPlainTextEdit(Animal)
        self.insuranceEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.insuranceEdit.setMaximumSize(QtCore.QSize(336, 100))
        self.insuranceEdit.setDocumentTitle(_fromUtf8(""))
        self.insuranceEdit.setPlainText(_fromUtf8(""))
        self.insuranceEdit.setObjectName(_fromUtf8("insuranceEdit"))
        self.verticalLayout.addWidget(self.insuranceEdit)
        self.label_14 = QtGui.QLabel(Animal)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(330, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout.addWidget(self.label_14)
        self.otherInfoTextEdit = QtGui.QPlainTextEdit(Animal)
        self.otherInfoTextEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.otherInfoTextEdit.setMaximumSize(QtCore.QSize(336, 200))
        self.otherInfoTextEdit.setObjectName(_fromUtf8("otherInfoTextEdit"))
        self.verticalLayout.addWidget(self.otherInfoTextEdit)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.deathcheckBox = QtGui.QCheckBox(Animal)
        self.deathcheckBox.setObjectName(_fromUtf8("deathcheckBox"))
        self.horizontalLayout_9.addWidget(self.deathcheckBox)
        self.dateEdit = QtGui.QDateEdit(Animal)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_9.addWidget(self.dateEdit)
        self.statusCheckBox = QtGui.QCheckBox(Animal)
        self.statusCheckBox.setObjectName(_fromUtf8("statusCheckBox"))
        self.horizontalLayout_9.addWidget(self.statusCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rightTabWidget = QtGui.QTabWidget(Animal)
        self.rightTabWidget.setObjectName(_fromUtf8("rightTabWidget"))
        self.vaccineTab = QtGui.QWidget()
        self.vaccineTab.setObjectName(_fromUtf8("vaccineTab"))
        self.vaccineLayout = QtGui.QVBoxLayout(self.vaccineTab)
        self.vaccineLayout.setObjectName(_fromUtf8("vaccineLayout"))
        self.rightTabWidget.addTab(self.vaccineTab, _fromUtf8(""))
        self.weigthControlTab = QtGui.QWidget()
        self.weigthControlTab.setObjectName(_fromUtf8("weigthControlTab"))
        self.weigthcontrolLayout = QtGui.QVBoxLayout(self.weigthControlTab)
        self.weigthcontrolLayout.setObjectName(_fromUtf8("weigthcontrolLayout"))
        self.rightTabWidget.addTab(self.weigthControlTab, _fromUtf8(""))
        self.pictureTab = QtGui.QWidget()
        self.pictureTab.setObjectName(_fromUtf8("pictureTab"))
        self.pictureLayout = QtGui.QVBoxLayout(self.pictureTab)
        self.pictureLayout.setObjectName(_fromUtf8("pictureLayout"))
        self.rightTabWidget.addTab(self.pictureTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.rightTabWidget, 1, 1, 1, 1)
        self.leftTabWidget = QtGui.QTabWidget(Animal)
        self.leftTabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.leftTabWidget.setObjectName(_fromUtf8("leftTabWidget"))
        self.medicineTab = QtGui.QWidget()
        self.medicineTab.setObjectName(_fromUtf8("medicineTab"))
        self.medicineLayout = QtGui.QVBoxLayout(self.medicineTab)
        self.medicineLayout.setObjectName(_fromUtf8("medicineLayout"))
        self.leftTabWidget.addTab(self.medicineTab, _fromUtf8(""))
        self.labTab = QtGui.QWidget()
        self.labTab.setObjectName(_fromUtf8("labTab"))
        self.labLayout = QtGui.QVBoxLayout(self.labTab)
        self.labLayout.setObjectName(_fromUtf8("labLayout"))
        self.leftTabWidget.addTab(self.labTab, _fromUtf8(""))
        self.phonerecepietab = QtGui.QWidget()
        self.phonerecepietab.setObjectName(_fromUtf8("phonerecepietab"))
        self.phoneLayout = QtGui.QVBoxLayout(self.phonerecepietab)
        self.phoneLayout.setObjectName(_fromUtf8("phoneLayout"))
        self.leftTabWidget.addTab(self.phonerecepietab, _fromUtf8(""))
        self.gridLayout.addWidget(self.leftTabWidget, 1, 0, 1, 1)
        self.examinationLayout = QtGui.QVBoxLayout()
        self.examinationLayout.setObjectName(_fromUtf8("examinationLayout"))
        self.gridLayout.addLayout(self.examinationLayout, 0, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout)
        self.horizontalLayout_8.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.buttons = QtGui.QHBoxLayout()
        self.buttons.setSpacing(0)
        self.buttons.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.buttons.setObjectName(_fromUtf8("buttons"))
        self.searchOwnersButton = QtGui.QPushButton(Animal)
        self.searchOwnersButton.setObjectName(_fromUtf8("searchOwnersButton"))
        self.buttons.addWidget(self.searchOwnersButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttons.addItem(spacerItem1)
        self.canselButton = QtGui.QPushButton(Animal)
        self.canselButton.setMinimumSize(QtCore.QSize(100, 0))
        self.canselButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.canselButton.setObjectName(_fromUtf8("canselButton"))
        self.buttons.addWidget(self.canselButton)
        self.saveButton = QtGui.QPushButton(Animal)
        self.saveButton.setMinimumSize(QtCore.QSize(100, 0))
        self.saveButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.buttons.addWidget(self.saveButton)
        self.saveAndExitButton = QtGui.QPushButton(Animal)
        self.saveAndExitButton.setObjectName(_fromUtf8("saveAndExitButton"))
        self.buttons.addWidget(self.saveAndExitButton)
        self.verticalLayout_2.addLayout(self.buttons)

        self.retranslateUi(Animal)
        self.rightTabWidget.setCurrentIndex(1)
        self.leftTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Animal)

    def retranslateUi(self, Animal):
        Animal.setWindowTitle(QtGui.QApplication.translate("Animal", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Animal", "Nimi", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLineEdit.setPlaceholderText(QtGui.QApplication.translate("Animal", "Nimi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Animal", "Virallinen nimi", None, QtGui.QApplication.UnicodeUTF8))
        self.officialNamelineEdit.setPlaceholderText(QtGui.QApplication.translate("Animal", "Virallinen nimi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Animal", "syntymäaika", None, QtGui.QApplication.UnicodeUTF8))
        self.birthdayEdit.setDisplayFormat(QtGui.QApplication.translate("Animal", "MM-dd-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Animal", "Laji", None, QtGui.QApplication.UnicodeUTF8))
        self.newSpecieButton.setToolTip(QtGui.QApplication.translate("Animal", "Lisää uusi laji", None, QtGui.QApplication.UnicodeUTF8))
        self.newSpecieButton.setText(QtGui.QApplication.translate("Animal", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Animal", "Rotu", None, QtGui.QApplication.UnicodeUTF8))
        self.newRaceButton.setToolTip(QtGui.QApplication.translate("Animal", "Lisää uusi rotu", None, QtGui.QApplication.UnicodeUTF8))
        self.newRaceButton.setText(QtGui.QApplication.translate("Animal", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Animal", "Sukupuoli", None, QtGui.QApplication.UnicodeUTF8))
        self.newSexButton.setToolTip(QtGui.QApplication.translate("Animal", "Lisää uusi sukupuoli", None, QtGui.QApplication.UnicodeUTF8))
        self.newSexButton.setText(QtGui.QApplication.translate("Animal", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Animal", "Väri", None, QtGui.QApplication.UnicodeUTF8))
        self.newColorButton.setToolTip(QtGui.QApplication.translate("Animal", "Lisää uusi väri", None, QtGui.QApplication.UnicodeUTF8))
        self.newColorButton.setText(QtGui.QApplication.translate("Animal", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Animal", "Rekisteri nro.", None, QtGui.QApplication.UnicodeUTF8))
        self.recNumlineEdit.setPlaceholderText(QtGui.QApplication.translate("Animal", "Rekisterinumero", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Animal", "Passi", None, QtGui.QApplication.UnicodeUTF8))
        self.passportLineEdit.setPlaceholderText(QtGui.QApplication.translate("Animal", "Passin numero", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Animal", "mikrosiru", None, QtGui.QApplication.UnicodeUTF8))
        self.microLineEdit.setPlaceholderText(QtGui.QApplication.translate("Animal", "Mikrosirun numero", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Animal", "Tatuointi", None, QtGui.QApplication.UnicodeUTF8))
        self.tattooLineEdit.setPlaceholderText(QtGui.QApplication.translate("Animal", "Tatuointi merkintä", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Animal", "vakuutus", None, QtGui.QApplication.UnicodeUTF8))
        self.insuranceEdit.setToolTip(QtGui.QApplication.translate("Animal", "Vakuutus numero ja tiedot tänne", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Animal", "Muuta", None, QtGui.QApplication.UnicodeUTF8))
        self.otherInfoTextEdit.setToolTip(QtGui.QApplication.translate("Animal", "Muut eläimen tiedot tänne", None, QtGui.QApplication.UnicodeUTF8))
        self.deathcheckBox.setText(QtGui.QApplication.translate("Animal", "Kuollut", None, QtGui.QApplication.UnicodeUTF8))
        self.statusCheckBox.setText(QtGui.QApplication.translate("Animal", "Vaativa", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTabWidget.setTabText(self.rightTabWidget.indexOf(self.vaccineTab), QtGui.QApplication.translate("Animal", "Rokotukset", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTabWidget.setTabText(self.rightTabWidget.indexOf(self.weigthControlTab), QtGui.QApplication.translate("Animal", "Painonseuranta", None, QtGui.QApplication.UnicodeUTF8))
        self.rightTabWidget.setTabText(self.rightTabWidget.indexOf(self.pictureTab), QtGui.QApplication.translate("Animal", "Kuvat", None, QtGui.QApplication.UnicodeUTF8))
        self.leftTabWidget.setTabText(self.leftTabWidget.indexOf(self.medicineTab), QtGui.QApplication.translate("Animal", "Lääkkeet", None, QtGui.QApplication.UnicodeUTF8))
        self.leftTabWidget.setTabText(self.leftTabWidget.indexOf(self.labTab), QtGui.QApplication.translate("Animal", "Labrata", None, QtGui.QApplication.UnicodeUTF8))
        self.leftTabWidget.setTabText(self.leftTabWidget.indexOf(self.phonerecepietab), QtGui.QApplication.translate("Animal", "Puhelinreseptit", None, QtGui.QApplication.UnicodeUTF8))
        self.searchOwnersButton.setText(QtGui.QApplication.translate("Animal", "Hae omistajat", None, QtGui.QApplication.UnicodeUTF8))
        self.canselButton.setText(QtGui.QApplication.translate("Animal", "Sulje", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Animal", "Tallenna", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAndExitButton.setText(QtGui.QApplication.translate("Animal", "Tallenna ja sulje", None, QtGui.QApplication.UnicodeUTF8))

