# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_bill.ui'
#
# Created: Sat Feb 28 14:31:08 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BillTab(object):
    def setupUi(self, BillTab):
        BillTab.setObjectName(_fromUtf8("BillTab"))
        BillTab.resize(959, 806)
        self.horizontalLayout_27 = QtGui.QHBoxLayout(BillTab)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(BillTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_12 = QtGui.QLabel(BillTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        self.ownerLabel = QtGui.QLabel(BillTab)
        self.ownerLabel.setObjectName(_fromUtf8("ownerLabel"))
        self.horizontalLayout_9.addWidget(self.ownerLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.clinic_radio_button = QtGui.QRadioButton(BillTab)
        self.clinic_radio_button.setChecked(True)
        self.clinic_radio_button.setObjectName(_fromUtf8("clinic_radio_button"))
        self.horizontalLayout_3.addWidget(self.clinic_radio_button)
        self.label_8 = QtGui.QLabel(BillTab)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.stackedWidget = QtGui.QStackedWidget(BillTab)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_18 = QtGui.QLabel(self.page)
        self.label_18.setMinimumSize(QtCore.QSize(105, 0))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_13.addWidget(self.label_18)
        self.clinicPriceSpinBox = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clinicPriceSpinBox.sizePolicy().hasHeightForWidth())
        self.clinicPriceSpinBox.setSizePolicy(sizePolicy)
        self.clinicPriceSpinBox.setObjectName(_fromUtf8("clinicPriceSpinBox"))
        self.horizontalLayout_13.addWidget(self.clinicPriceSpinBox)
        self.label_28 = QtGui.QLabel(self.page)
        self.label_28.setMinimumSize(QtCore.QSize(8, 0))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_13.addWidget(self.label_28)
        self.ALV1_1 = QtGui.QLabel(self.page)
        self.ALV1_1.setMinimumSize(QtCore.QSize(32, 0))
        self.ALV1_1.setObjectName(_fromUtf8("ALV1_1"))
        self.horizontalLayout_13.addWidget(self.ALV1_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_10 = QtGui.QLabel(self.page)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.setDefaultclinicPriceButton = QtGui.QPushButton(self.page)
        self.setDefaultclinicPriceButton.setObjectName(_fromUtf8("setDefaultclinicPriceButton"))
        self.horizontalLayout_4.addWidget(self.setDefaultclinicPriceButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_33 = QtGui.QLabel(self.page_2)
        self.label_33.setMinimumSize(QtCore.QSize(105, 24))
        self.label_33.setMaximumSize(QtCore.QSize(105, 24))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_17.addWidget(self.label_33)
        self.KmSpinBox = QtGui.QDoubleSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KmSpinBox.sizePolicy().hasHeightForWidth())
        self.KmSpinBox.setSizePolicy(sizePolicy)
        self.KmSpinBox.setMaximum(99999999.99)
        self.KmSpinBox.setObjectName(_fromUtf8("KmSpinBox"))
        self.horizontalLayout_17.addWidget(self.KmSpinBox)
        self.label_34 = QtGui.QLabel(self.page_2)
        self.label_34.setMinimumSize(QtCore.QSize(40, 0))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_17.addWidget(self.label_34)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_35 = QtGui.QLabel(self.page_2)
        self.label_35.setMinimumSize(QtCore.QSize(105, 24))
        self.label_35.setMaximumSize(QtCore.QSize(105, 24))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_18.addWidget(self.label_35)
        self.KmPriceSpinBox = QtGui.QDoubleSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KmPriceSpinBox.sizePolicy().hasHeightForWidth())
        self.KmPriceSpinBox.setSizePolicy(sizePolicy)
        self.KmPriceSpinBox.setMaximum(99999999.99)
        self.KmPriceSpinBox.setObjectName(_fromUtf8("KmPriceSpinBox"))
        self.horizontalLayout_18.addWidget(self.KmPriceSpinBox)
        self.label_36 = QtGui.QLabel(self.page_2)
        self.label_36.setMinimumSize(QtCore.QSize(40, 0))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_18.addWidget(self.label_36)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_37 = QtGui.QLabel(self.page_2)
        self.label_37.setMinimumSize(QtCore.QSize(105, 24))
        self.label_37.setMaximumSize(QtCore.QSize(105, 24))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_19.addWidget(self.label_37)
        self.visitPriceSpinBox = QtGui.QDoubleSpinBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visitPriceSpinBox.sizePolicy().hasHeightForWidth())
        self.visitPriceSpinBox.setSizePolicy(sizePolicy)
        self.visitPriceSpinBox.setMaximum(99999999.99)
        self.visitPriceSpinBox.setObjectName(_fromUtf8("visitPriceSpinBox"))
        self.horizontalLayout_19.addWidget(self.visitPriceSpinBox)
        self.label_38 = QtGui.QLabel(self.page_2)
        self.label_38.setMinimumSize(QtCore.QSize(8, 0))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_19.addWidget(self.label_38)
        self.ALV1_6 = QtGui.QLabel(self.page_2)
        self.ALV1_6.setMinimumSize(QtCore.QSize(32, 0))
        self.ALV1_6.setObjectName(_fromUtf8("ALV1_6"))
        self.horizontalLayout_19.addWidget(self.ALV1_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.line_4 = QtGui.QFrame(BillTab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_16 = QtGui.QLabel(BillTab)
        self.label_16.setMinimumSize(QtCore.QSize(105, 24))
        self.label_16.setMaximumSize(QtCore.QSize(105, 24))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_11.addWidget(self.label_16)
        self.operationSpinBox = QtGui.QDoubleSpinBox(BillTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operationSpinBox.sizePolicy().hasHeightForWidth())
        self.operationSpinBox.setSizePolicy(sizePolicy)
        self.operationSpinBox.setMaximum(99999999.99)
        self.operationSpinBox.setObjectName(_fromUtf8("operationSpinBox"))
        self.horizontalLayout_11.addWidget(self.operationSpinBox)
        self.label_25 = QtGui.QLabel(BillTab)
        self.label_25.setMinimumSize(QtCore.QSize(8, 0))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_11.addWidget(self.label_25)
        self.ALV1_2 = QtGui.QLabel(BillTab)
        self.ALV1_2.setMinimumSize(QtCore.QSize(32, 0))
        self.ALV1_2.setObjectName(_fromUtf8("ALV1_2"))
        self.horizontalLayout_11.addWidget(self.ALV1_2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(BillTab)
        self.label_17.setMinimumSize(QtCore.QSize(105, 24))
        self.label_17.setMaximumSize(QtCore.QSize(105, 24))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.accessoriesSpinBox = QtGui.QDoubleSpinBox(BillTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accessoriesSpinBox.sizePolicy().hasHeightForWidth())
        self.accessoriesSpinBox.setSizePolicy(sizePolicy)
        self.accessoriesSpinBox.setMaximum(99999999.99)
        self.accessoriesSpinBox.setObjectName(_fromUtf8("accessoriesSpinBox"))
        self.horizontalLayout_12.addWidget(self.accessoriesSpinBox)
        self.label_26 = QtGui.QLabel(BillTab)
        self.label_26.setMinimumSize(QtCore.QSize(8, 0))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_12.addWidget(self.label_26)
        self.ALV1_3 = QtGui.QLabel(BillTab)
        self.ALV1_3.setMinimumSize(QtCore.QSize(32, 0))
        self.ALV1_3.setObjectName(_fromUtf8("ALV1_3"))
        self.horizontalLayout_12.addWidget(self.ALV1_3)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_31 = QtGui.QLabel(BillTab)
        self.label_31.setMinimumSize(QtCore.QSize(105, 24))
        self.label_31.setMaximumSize(QtCore.QSize(105, 24))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_16.addWidget(self.label_31)
        self.labSpinBox = QtGui.QDoubleSpinBox(BillTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labSpinBox.sizePolicy().hasHeightForWidth())
        self.labSpinBox.setSizePolicy(sizePolicy)
        self.labSpinBox.setMaximum(99999999.99)
        self.labSpinBox.setObjectName(_fromUtf8("labSpinBox"))
        self.horizontalLayout_16.addWidget(self.labSpinBox)
        self.label_32 = QtGui.QLabel(BillTab)
        self.label_32.setMinimumSize(QtCore.QSize(8, 0))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_16.addWidget(self.label_32)
        self.ALV1_4 = QtGui.QLabel(BillTab)
        self.ALV1_4.setMinimumSize(QtCore.QSize(32, 0))
        self.ALV1_4.setObjectName(_fromUtf8("ALV1_4"))
        self.horizontalLayout_16.addWidget(self.ALV1_4)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.extraPercentLabel = QtGui.QLabel(BillTab)
        self.extraPercentLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.extraPercentLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.extraPercentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.extraPercentLabel.setObjectName(_fromUtf8("extraPercentLabel"))
        self.horizontalLayout_5.addWidget(self.extraPercentLabel)
        self.label_14 = QtGui.QLabel(BillTab)
        self.label_14.setMinimumSize(QtCore.QSize(55, 0))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_5.addWidget(self.label_14)
        self.precentSlider = QtGui.QSlider(BillTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.precentSlider.sizePolicy().hasHeightForWidth())
        self.precentSlider.setSizePolicy(sizePolicy)
        self.precentSlider.setMinimum(-100)
        self.precentSlider.setMaximum(500)
        self.precentSlider.setOrientation(QtCore.Qt.Horizontal)
        self.precentSlider.setObjectName(_fromUtf8("precentSlider"))
        self.horizontalLayout_5.addWidget(self.precentSlider)
        self.label_7 = QtGui.QLabel(BillTab)
        self.label_7.setMinimumSize(QtCore.QSize(40, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_5 = QtGui.QFrame(BillTab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_22 = QtGui.QLabel(BillTab)
        self.label_22.setMinimumSize(QtCore.QSize(105, 24))
        self.label_22.setMaximumSize(QtCore.QSize(105, 24))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_14.addWidget(self.label_22)
        self.medicineSpinBox = QtGui.QDoubleSpinBox(BillTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medicineSpinBox.sizePolicy().hasHeightForWidth())
        self.medicineSpinBox.setSizePolicy(sizePolicy)
        self.medicineSpinBox.setMaximum(99999999.99)
        self.medicineSpinBox.setObjectName(_fromUtf8("medicineSpinBox"))
        self.horizontalLayout_14.addWidget(self.medicineSpinBox)
        self.label_29 = QtGui.QLabel(BillTab)
        self.label_29.setMinimumSize(QtCore.QSize(8, 0))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_14.addWidget(self.label_29)
        self.ALV2_1 = QtGui.QLabel(BillTab)
        self.ALV2_1.setMinimumSize(QtCore.QSize(32, 0))
        self.ALV2_1.setObjectName(_fromUtf8("ALV2_1"))
        self.horizontalLayout_14.addWidget(self.ALV2_1)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.line_6 = QtGui.QFrame(BillTab)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_23 = QtGui.QLabel(BillTab)
        self.label_23.setMinimumSize(QtCore.QSize(105, 24))
        self.label_23.setMaximumSize(QtCore.QSize(105, 24))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_15.addWidget(self.label_23)
        self.dietSpinBox = QtGui.QDoubleSpinBox(BillTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dietSpinBox.sizePolicy().hasHeightForWidth())
        self.dietSpinBox.setSizePolicy(sizePolicy)
        self.dietSpinBox.setMaximum(99999999.99)
        self.dietSpinBox.setObjectName(_fromUtf8("dietSpinBox"))
        self.horizontalLayout_15.addWidget(self.dietSpinBox)
        self.label_30 = QtGui.QLabel(BillTab)
        self.label_30.setMinimumSize(QtCore.QSize(8, 0))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_15.addWidget(self.label_30)
        self.ALV3_1 = QtGui.QLabel(BillTab)
        self.ALV3_1.setMinimumSize(QtCore.QSize(32, 0))
        self.ALV3_1.setObjectName(_fromUtf8("ALV3_1"))
        self.horizontalLayout_15.addWidget(self.ALV3_1)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.label_6 = QtGui.QLabel(BillTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.otherInfoTextEdit = QtGui.QPlainTextEdit(BillTab)
        self.otherInfoTextEdit.setObjectName(_fromUtf8("otherInfoTextEdit"))
        self.verticalLayout.addWidget(self.otherInfoTextEdit)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(BillTab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.indexNumberLabel = QtGui.QLabel(BillTab)
        self.indexNumberLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.indexNumberLabel.setObjectName(_fromUtf8("indexNumberLabel"))
        self.horizontalLayout_10.addWidget(self.indexNumberLabel)
        self.horizontalLayout_10.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(BillTab)
        self.label_5.setMinimumSize(QtCore.QSize(105, 0))
        self.label_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.paymentComboBox = QtGui.QComboBox(BillTab)
        self.paymentComboBox.setObjectName(_fromUtf8("paymentComboBox"))
        self.horizontalLayout_8.addWidget(self.paymentComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(BillTab)
        self.label_2.setMinimumSize(QtCore.QSize(105, 0))
        self.label_2.setMaximumSize(QtCore.QSize(105, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.paidSpinBox = QtGui.QDoubleSpinBox(BillTab)
        self.paidSpinBox.setMaximum(99999999.99)
        self.paidSpinBox.setObjectName(_fromUtf8("paidSpinBox"))
        self.horizontalLayout.addWidget(self.paidSpinBox)
        self.label_39 = QtGui.QLabel(BillTab)
        self.label_39.setMinimumSize(QtCore.QSize(8, 0))
        self.label_39.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout.addWidget(self.label_39)
        self.all_pushButton = QtGui.QPushButton(BillTab)
        self.all_pushButton.setMinimumSize(QtCore.QSize(32, 0))
        self.all_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.all_pushButton.setObjectName(_fromUtf8("all_pushButton"))
        self.horizontalLayout.addWidget(self.all_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(BillTab)
        self.label_4.setMinimumSize(QtCore.QSize(105, 0))
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.paidDateEdit = QtGui.QDateEdit(BillTab)
        self.paidDateEdit.setCalendarPopup(True)
        self.paidDateEdit.setObjectName(_fromUtf8("paidDateEdit"))
        self.horizontalLayout_7.addWidget(self.paidDateEdit)
        self.nowButton = QtGui.QPushButton(BillTab)
        self.nowButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.nowButton.setObjectName(_fromUtf8("nowButton"))
        self.horizontalLayout_7.addWidget(self.nowButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(BillTab)
        self.label_3.setMinimumSize(QtCore.QSize(105, 0))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.DueDateEdit = QtGui.QDateEdit(BillTab)
        self.DueDateEdit.setCalendarPopup(True)
        self.DueDateEdit.setObjectName(_fromUtf8("DueDateEdit"))
        self.horizontalLayout_6.addWidget(self.DueDateEdit)
        self.DueDateTimeComboBox = QtGui.QComboBox(BillTab)
        self.DueDateTimeComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.DueDateTimeComboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.DueDateTimeComboBox.setEditable(False)
        self.DueDateTimeComboBox.setObjectName(_fromUtf8("DueDateTimeComboBox"))
        self.horizontalLayout_6.addWidget(self.DueDateTimeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.savePushButton = QtGui.QPushButton(BillTab)
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.horizontalLayout_2.addWidget(self.savePushButton)
        self.toVisitButton = QtGui.QPushButton(BillTab)
        self.toVisitButton.setObjectName(_fromUtf8("toVisitButton"))
        self.horizontalLayout_2.addWidget(self.toVisitButton)
        self.updateFromVisitButton = QtGui.QPushButton(BillTab)
        self.updateFromVisitButton.setObjectName(_fromUtf8("updateFromVisitButton"))
        self.horizontalLayout_2.addWidget(self.updateFromVisitButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.printButton = QtGui.QPushButton(BillTab)
        self.printButton.setObjectName(_fromUtf8("printButton"))
        self.horizontalLayout_2.addWidget(self.printButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_27.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_40 = QtGui.QLabel(BillTab)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_20.addWidget(self.label_40)
        self.ALV1_7 = QtGui.QLabel(BillTab)
        self.ALV1_7.setObjectName(_fromUtf8("ALV1_7"))
        self.horizontalLayout_20.addWidget(self.ALV1_7)
        self.price_ALV1_total_label = QtGui.QLabel(BillTab)
        self.price_ALV1_total_label.setObjectName(_fromUtf8("price_ALV1_total_label"))
        self.horizontalLayout_20.addWidget(self.price_ALV1_total_label)
        self.label_41 = QtGui.QLabel(BillTab)
        self.label_41.setMinimumSize(QtCore.QSize(40, 0))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_20.addWidget(self.label_41)
        self.horizontalLayout_20.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_42 = QtGui.QLabel(BillTab)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_21.addWidget(self.label_42)
        self.ALV1_total = QtGui.QLabel(BillTab)
        self.ALV1_total.setObjectName(_fromUtf8("ALV1_total"))
        self.horizontalLayout_21.addWidget(self.ALV1_total)
        self.label_43 = QtGui.QLabel(BillTab)
        self.label_43.setMinimumSize(QtCore.QSize(40, 0))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_21.addWidget(self.label_43)
        self.horizontalLayout_21.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.line_3 = QtGui.QFrame(BillTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_46 = QtGui.QLabel(BillTab)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_23.addWidget(self.label_46)
        self.ALV2_2 = QtGui.QLabel(BillTab)
        self.ALV2_2.setObjectName(_fromUtf8("ALV2_2"))
        self.horizontalLayout_23.addWidget(self.ALV2_2)
        self.price_ALV2_total_label = QtGui.QLabel(BillTab)
        self.price_ALV2_total_label.setObjectName(_fromUtf8("price_ALV2_total_label"))
        self.horizontalLayout_23.addWidget(self.price_ALV2_total_label)
        self.label_47 = QtGui.QLabel(BillTab)
        self.label_47.setMinimumSize(QtCore.QSize(40, 0))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_23.addWidget(self.label_47)
        self.horizontalLayout_23.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_44 = QtGui.QLabel(BillTab)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_22.addWidget(self.label_44)
        self.ALV2_total = QtGui.QLabel(BillTab)
        self.ALV2_total.setObjectName(_fromUtf8("ALV2_total"))
        self.horizontalLayout_22.addWidget(self.ALV2_total)
        self.label_45 = QtGui.QLabel(BillTab)
        self.label_45.setMinimumSize(QtCore.QSize(40, 0))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_22.addWidget(self.label_45)
        self.horizontalLayout_22.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.line_2 = QtGui.QFrame(BillTab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_52 = QtGui.QLabel(BillTab)
        self.label_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_26.addWidget(self.label_52)
        self.ALV3_2 = QtGui.QLabel(BillTab)
        self.ALV3_2.setObjectName(_fromUtf8("ALV3_2"))
        self.horizontalLayout_26.addWidget(self.ALV3_2)
        self.price_ALV3_total_label = QtGui.QLabel(BillTab)
        self.price_ALV3_total_label.setObjectName(_fromUtf8("price_ALV3_total_label"))
        self.horizontalLayout_26.addWidget(self.price_ALV3_total_label)
        self.label_53 = QtGui.QLabel(BillTab)
        self.label_53.setMinimumSize(QtCore.QSize(40, 0))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_26.addWidget(self.label_53)
        self.horizontalLayout_26.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_48 = QtGui.QLabel(BillTab)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_24.addWidget(self.label_48)
        self.ALV3_total = QtGui.QLabel(BillTab)
        self.ALV3_total.setObjectName(_fromUtf8("ALV3_total"))
        self.horizontalLayout_24.addWidget(self.ALV3_total)
        self.label_49 = QtGui.QLabel(BillTab)
        self.label_49.setMinimumSize(QtCore.QSize(40, 0))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_24.addWidget(self.label_49)
        self.horizontalLayout_24.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.line = QtGui.QFrame(BillTab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_11 = QtGui.QLabel(BillTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_25.addWidget(self.label_11)
        self.roundButton1 = QtGui.QPushButton(BillTab)
        self.roundButton1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roundButton1.sizePolicy().hasHeightForWidth())
        self.roundButton1.setSizePolicy(sizePolicy)
        self.roundButton1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.roundButton1.setObjectName(_fromUtf8("roundButton1"))
        self.horizontalLayout_25.addWidget(self.roundButton1)
        self.roundButton05 = QtGui.QPushButton(BillTab)
        self.roundButton05.setMaximumSize(QtCore.QSize(40, 16777215))
        self.roundButton05.setObjectName(_fromUtf8("roundButton05"))
        self.horizontalLayout_25.addWidget(self.roundButton05)
        self.roundButton005 = QtGui.QPushButton(BillTab)
        self.roundButton005.setMaximumSize(QtCore.QSize(40, 16777215))
        self.roundButton005.setObjectName(_fromUtf8("roundButton005"))
        self.horizontalLayout_25.addWidget(self.roundButton005)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem4)
        self.label_50 = QtGui.QLabel(BillTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_25.addWidget(self.label_50)
        self.endPriceLabel = QtGui.QLabel(BillTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.endPriceLabel.setFont(font)
        self.endPriceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.endPriceLabel.setObjectName(_fromUtf8("endPriceLabel"))
        self.horizontalLayout_25.addWidget(self.endPriceLabel)
        self.label_51 = QtGui.QLabel(BillTab)
        self.label_51.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_25.addWidget(self.label_51)
        self.horizontalLayout_25.setStretch(5, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_27.addLayout(self.verticalLayout_5)

        self.retranslateUi(BillTab)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BillTab)

    def retranslateUi(self, BillTab):
        BillTab.setWindowTitle(_translate("BillTab", "Form", None))
        self.label.setText(_translate("BillTab", "Lasku", None))
        self.label_12.setText(_translate("BillTab", "Omistaja:", None))
        self.ownerLabel.setText(_translate("BillTab", "Nimi", None))
        self.clinic_radio_button.setText(_translate("BillTab", "Klinikkakäynti", None))
        self.label_8.setText(_translate("BillTab", "ALV", None))
        self.label_18.setText(_translate("BillTab", "Klinikkamaksu", None))
        self.label_28.setText(_translate("BillTab", "€", None))
        self.ALV1_1.setText(_translate("BillTab", "ALV1", None))
        self.label_10.setText(_translate("BillTab", "Oletus kinikkamaksu:", None))
        self.setDefaultclinicPriceButton.setText(_translate("BillTab", "Aseta", None))
        self.label_33.setText(_translate("BillTab", "Kilometrit", None))
        self.label_34.setText(_translate("BillTab", "km", None))
        self.label_35.setText(_translate("BillTab", "Kilometrikorvaus", None))
        self.label_36.setText(_translate("BillTab", "€", None))
        self.label_37.setText(_translate("BillTab", "Käyntimaksu", None))
        self.label_38.setText(_translate("BillTab", "€", None))
        self.ALV1_6.setText(_translate("BillTab", "ALV1", None))
        self.label_16.setText(_translate("BillTab", "Toimenpiteet", None))
        self.label_25.setText(_translate("BillTab", "€", None))
        self.ALV1_2.setText(_translate("BillTab", "ALV1", None))
        self.label_17.setText(_translate("BillTab", "Tarvikkeet", None))
        self.label_26.setText(_translate("BillTab", "€", None))
        self.ALV1_3.setText(_translate("BillTab", "ALV1", None))
        self.label_31.setText(_translate("BillTab", "Laboratorio", None))
        self.label_32.setText(_translate("BillTab", "€", None))
        self.ALV1_4.setText(_translate("BillTab", "ALV1", None))
        self.extraPercentLabel.setText(_translate("BillTab", "0", None))
        self.label_14.setText(_translate("BillTab", "-100%", None))
        self.label_7.setText(_translate("BillTab", "500%", None))
        self.label_22.setText(_translate("BillTab", "Lääkkeet", None))
        self.label_29.setText(_translate("BillTab", "€", None))
        self.ALV2_1.setText(_translate("BillTab", "ALV2", None))
        self.label_23.setText(_translate("BillTab", "Diettituotteet", None))
        self.label_30.setText(_translate("BillTab", "€", None))
        self.ALV3_1.setText(_translate("BillTab", "ALV3", None))
        self.label_6.setText(_translate("BillTab", "Muuta huomioitavaa", None))
        self.label_9.setText(_translate("BillTab", "Viitenumero:", None))
        self.indexNumberLabel.setText(_translate("BillTab", "TextLabel", None))
        self.label_5.setText(_translate("BillTab", "Maksutapa", None))
        self.label_2.setText(_translate("BillTab", "Maksettu osuus", None))
        self.label_39.setText(_translate("BillTab", "€", None))
        self.all_pushButton.setText(_translate("BillTab", "Kaikki", None))
        self.label_4.setText(_translate("BillTab", "Maksettu", None))
        self.nowButton.setText(_translate("BillTab", "Nyt", None))
        self.label_3.setText(_translate("BillTab", "Eräpäivä", None))
        self.savePushButton.setText(_translate("BillTab", "Tallenna", None))
        self.toVisitButton.setText(_translate("BillTab", "Käyntiin", None))
        self.updateFromVisitButton.setText(_translate("BillTab", "Hae tiedot", None))
        self.printButton.setText(_translate("BillTab", "Tulosta", None))
        self.label_40.setText(_translate("BillTab", "Hinta", None))
        self.ALV1_7.setText(_translate("BillTab", "ALV1", None))
        self.price_ALV1_total_label.setText(_translate("BillTab", "0.00", None))
        self.label_41.setText(_translate("BillTab", "€", None))
        self.label_42.setText(_translate("BillTab", "ALV:", None))
        self.ALV1_total.setText(_translate("BillTab", "0.00", None))
        self.label_43.setText(_translate("BillTab", "€", None))
        self.label_46.setText(_translate("BillTab", "Hinta", None))
        self.ALV2_2.setText(_translate("BillTab", "ALV2", None))
        self.price_ALV2_total_label.setText(_translate("BillTab", "0.00", None))
        self.label_47.setText(_translate("BillTab", "€", None))
        self.label_44.setText(_translate("BillTab", "ALV:", None))
        self.ALV2_total.setText(_translate("BillTab", "0.00", None))
        self.label_45.setText(_translate("BillTab", "€", None))
        self.label_52.setText(_translate("BillTab", "Hinta", None))
        self.ALV3_2.setText(_translate("BillTab", "ALV3", None))
        self.price_ALV3_total_label.setText(_translate("BillTab", "0.00", None))
        self.label_53.setText(_translate("BillTab", "€", None))
        self.label_48.setText(_translate("BillTab", "ALV:", None))
        self.ALV3_total.setText(_translate("BillTab", "0.00", None))
        self.label_49.setText(_translate("BillTab", "€", None))
        self.label_11.setText(_translate("BillTab", "Pyöristä", None))
        self.roundButton1.setText(_translate("BillTab", "1€", None))
        self.roundButton05.setText(_translate("BillTab", "0.50€", None))
        self.roundButton005.setText(_translate("BillTab", "0,05€", None))
        self.label_50.setText(_translate("BillTab", "Summa:", None))
        self.endPriceLabel.setText(_translate("BillTab", "0.00", None))
        self.label_51.setText(_translate("BillTab", "€", None))

