# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_itemcreator.ui'
#
# Created: Thu Aug 29 09:57:34 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ItemCreatorDialog(object):
    def setupUi(self, ItemCreatorDialog):
        ItemCreatorDialog.setObjectName(_fromUtf8("ItemCreatorDialog"))
        ItemCreatorDialog.resize(427, 566)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ItemCreatorDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(ItemCreatorDialog)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.nameEdit = QtGui.QLineEdit(ItemCreatorDialog)
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.horizontalLayout_5.addWidget(self.nameEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(ItemCreatorDialog)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.typeSelectComboBox = QtGui.QComboBox(ItemCreatorDialog)
        self.typeSelectComboBox.setObjectName(_fromUtf8("typeSelectComboBox"))
        self.horizontalLayout.addWidget(self.typeSelectComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_10 = QtGui.QLabel(ItemCreatorDialog)
        self.label_10.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.alvLabel = QtGui.QLabel(ItemCreatorDialog)
        self.alvLabel.setObjectName(_fromUtf8("alvLabel"))
        self.horizontalLayout_8.addWidget(self.alvLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(ItemCreatorDialog)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.priceSpinBox = QtGui.QDoubleSpinBox(ItemCreatorDialog)
        self.priceSpinBox.setMaximum(999999999.99)
        self.priceSpinBox.setSingleStep(0.05)
        self.priceSpinBox.setObjectName(_fromUtf8("priceSpinBox"))
        self.horizontalLayout_4.addWidget(self.priceSpinBox)
        self.label_7 = QtGui.QLabel(ItemCreatorDialog)
        self.label_7.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(ItemCreatorDialog)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.stockPriceSpinBox = QtGui.QDoubleSpinBox(ItemCreatorDialog)
        self.stockPriceSpinBox.setMaximum(999999999.99)
        self.stockPriceSpinBox.setSingleStep(0.05)
        self.stockPriceSpinBox.setObjectName(_fromUtf8("stockPriceSpinBox"))
        self.horizontalLayout_3.addWidget(self.stockPriceSpinBox)
        self.label_8 = QtGui.QLabel(ItemCreatorDialog)
        self.label_8.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(ItemCreatorDialog)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.BarCodeEdit = QtGui.QLineEdit(ItemCreatorDialog)
        self.BarCodeEdit.setObjectName(_fromUtf8("BarCodeEdit"))
        self.horizontalLayout_2.addWidget(self.BarCodeEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.durationLabel = QtGui.QLabel(ItemCreatorDialog)
        self.durationLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.durationLabel.setObjectName(_fromUtf8("durationLabel"))
        self.horizontalLayout_6.addWidget(self.durationLabel)
        self.preSetDurationsComboBox = QtGui.QComboBox(ItemCreatorDialog)
        self.preSetDurationsComboBox.setObjectName(_fromUtf8("preSetDurationsComboBox"))
        self.horizontalLayout_6.addWidget(self.preSetDurationsComboBox)
        self.daySpinEdit = QtGui.QSpinBox(ItemCreatorDialog)
        self.daySpinEdit.setMaximum(9999999)
        self.daySpinEdit.setObjectName(_fromUtf8("daySpinEdit"))
        self.horizontalLayout_6.addWidget(self.daySpinEdit)
        self.label_9 = QtGui.QLabel(ItemCreatorDialog)
        self.label_9.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(ItemCreatorDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.plainTextEdit = QtGui.QPlainTextEdit(ItemCreatorDialog)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.canselButton = QtGui.QPushButton(ItemCreatorDialog)
        self.canselButton.setObjectName(_fromUtf8("canselButton"))
        self.horizontalLayout_7.addWidget(self.canselButton)
        self.saveButton = QtGui.QPushButton(ItemCreatorDialog)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_7.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.retranslateUi(ItemCreatorDialog)
        QtCore.QMetaObject.connectSlotsByName(ItemCreatorDialog)

    def retranslateUi(self, ItemCreatorDialog):
        ItemCreatorDialog.setWindowTitle(QtGui.QApplication.translate("ItemCreatorDialog", "Tuotemuokkain", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Nimi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Tyyppi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ItemCreatorDialog", "ALV:", None, QtGui.QApplication.UnicodeUTF8))
        self.alvLabel.setText(QtGui.QApplication.translate("ItemCreatorDialog", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Hinta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ItemCreatorDialog", "€", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Varastohinta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ItemCreatorDialog", "€", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Viivakoodi", None, QtGui.QApplication.UnicodeUTF8))
        self.durationLabel.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Uusintaväli", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ItemCreatorDialog", "d", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Kuvaus", None, QtGui.QApplication.UnicodeUTF8))
        self.canselButton.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Hylkää", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("ItemCreatorDialog", "Tallenna", None, QtGui.QApplication.UnicodeUTF8))

