# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_operationcreator.ui'
#
# Created: Sun Feb  9 00:21:14 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OperationCreator(object):
    def setupUi(self, OperationCreator):
        OperationCreator.setObjectName(_fromUtf8("OperationCreator"))
        OperationCreator.resize(766, 496)
        self.verticalLayout_2 = QtGui.QVBoxLayout(OperationCreator)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setHorizontalSpacing(1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(OperationCreator)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_5)
        self.label = QtGui.QLabel(OperationCreator)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.nameEdit = QtGui.QLineEdit(OperationCreator)
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nameEdit)
        self.label_2 = QtGui.QLabel(OperationCreator)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(OperationCreator)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.typeComboBox = QtGui.QComboBox(OperationCreator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeComboBox.sizePolicy().hasHeightForWidth())
        self.typeComboBox.setSizePolicy(sizePolicy)
        self.typeComboBox.setObjectName(_fromUtf8("typeComboBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.typeComboBox)
        self.label_4 = QtGui.QLabel(OperationCreator)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.descriptionTextEdit = QtGui.QPlainTextEdit(OperationCreator)
        self.descriptionTextEdit.setObjectName(_fromUtf8("descriptionTextEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.descriptionTextEdit)
        self.priceSpinBox = QtGui.QDoubleSpinBox(OperationCreator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceSpinBox.sizePolicy().hasHeightForWidth())
        self.priceSpinBox.setSizePolicy(sizePolicy)
        self.priceSpinBox.setMaximum(999999999.99)
        self.priceSpinBox.setObjectName(_fromUtf8("priceSpinBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.priceSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.stackedWidget = QtGui.QStackedWidget(OperationCreator)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.emptyPage = QtGui.QWidget()
        self.emptyPage.setObjectName(_fromUtf8("emptyPage"))
        self.stackedWidget.addWidget(self.emptyPage)
        self.vaccinePage = QtGui.QWidget()
        self.vaccinePage.setObjectName(_fromUtf8("vaccinePage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.vaccinePage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.vaccinePage)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.searchLineEditLayout = QtGui.QHBoxLayout()
        self.searchLineEditLayout.setObjectName(_fromUtf8("searchLineEditLayout"))
        self.editmedicine = QtGui.QPushButton(self.vaccinePage)
        self.editmedicine.setMaximumSize(QtCore.QSize(150, 16777215))
        self.editmedicine.setObjectName(_fromUtf8("editmedicine"))
        self.searchLineEditLayout.addWidget(self.editmedicine)
        self.verticalLayout_3.addLayout(self.searchLineEditLayout)
        self.resitCheckBox = QtGui.QCheckBox(self.vaccinePage)
        self.resitCheckBox.setObjectName(_fromUtf8("resitCheckBox"))
        self.verticalLayout_3.addWidget(self.resitCheckBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.vaccinePage)
        self.label_6.setEnabled(False)
        self.label_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.durationspinBox = QtGui.QSpinBox(self.vaccinePage)
        self.durationspinBox.setEnabled(False)
        self.durationspinBox.setMaximum(999999999)
        self.durationspinBox.setObjectName(_fromUtf8("durationspinBox"))
        self.horizontalLayout.addWidget(self.durationspinBox)
        self.label_8 = QtGui.QLabel(self.vaccinePage)
        self.label_8.setEnabled(False)
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.getFromMedicineButton = QtGui.QPushButton(self.vaccinePage)
        self.getFromMedicineButton.setEnabled(False)
        self.getFromMedicineButton.setObjectName(_fromUtf8("getFromMedicineButton"))
        self.horizontalLayout.addWidget(self.getFromMedicineButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.vaccinePage)
        self.itemPage = QtGui.QWidget()
        self.itemPage.setObjectName(_fromUtf8("itemPage"))
        self.itemPageLayout = QtGui.QHBoxLayout(self.itemPage)
        self.itemPageLayout.setObjectName(_fromUtf8("itemPageLayout"))
        self.stackedWidget.addWidget(self.itemPage)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.closeButton = QtGui.QPushButton(OperationCreator)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.saveButton = QtGui.QPushButton(OperationCreator)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(OperationCreator)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OperationCreator)
        OperationCreator.setTabOrder(self.nameEdit, self.priceSpinBox)
        OperationCreator.setTabOrder(self.priceSpinBox, self.typeComboBox)
        OperationCreator.setTabOrder(self.typeComboBox, self.descriptionTextEdit)
        OperationCreator.setTabOrder(self.descriptionTextEdit, self.editmedicine)
        OperationCreator.setTabOrder(self.editmedicine, self.resitCheckBox)
        OperationCreator.setTabOrder(self.resitCheckBox, self.durationspinBox)
        OperationCreator.setTabOrder(self.durationspinBox, self.getFromMedicineButton)
        OperationCreator.setTabOrder(self.getFromMedicineButton, self.saveButton)
        OperationCreator.setTabOrder(self.saveButton, self.closeButton)

    def retranslateUi(self, OperationCreator):
        OperationCreator.setWindowTitle(_translate("OperationCreator", "Operaatiopohjan luonti", None))
        self.label_5.setText(_translate("OperationCreator", "Operaatiopohja", None))
        self.label.setText(_translate("OperationCreator", "Nimi", None))
        self.nameEdit.setPlaceholderText(_translate("OperationCreator", "Operaation nimi", None))
        self.label_2.setText(_translate("OperationCreator", "Hinta", None))
        self.label_3.setText(_translate("OperationCreator", "Tyyppi", None))
        self.label_4.setText(_translate("OperationCreator", "Kuvaus", None))
        self.label_7.setText(_translate("OperationCreator", "Lääkevalinta", None))
        self.editmedicine.setText(_translate("OperationCreator", "Muokkaa lääkettä", None))
        self.resitCheckBox.setText(_translate("OperationCreator", "Uusittava", None))
        self.label_6.setText(_translate("OperationCreator", "Uusintaväli", None))
        self.label_8.setText(_translate("OperationCreator", "vrk", None))
        self.getFromMedicineButton.setText(_translate("OperationCreator", "Hae lääkkeestä", None))
        self.closeButton.setText(_translate("OperationCreator", "Hylkää", None))
        self.saveButton.setText(_translate("OperationCreator", "Tallenna", None))

