# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ownertab.ui'
#
# Created: Sat Apr 13 16:28:55 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OwnerTab(object):
    def setupUi(self, OwnerTab):
        OwnerTab.setObjectName(_fromUtf8("OwnerTab"))
        OwnerTab.resize(817, 578)
        self.verticalLayout_3 = QtGui.QVBoxLayout(OwnerTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(OwnerTab)
        self.label_2.setMinimumSize(QtCore.QSize(100, 25))
        self.label_2.setMaximumSize(QtCore.QSize(100, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.nameEdit = QtGui.QLineEdit(OwnerTab)
        self.nameEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.nameEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.nameEdit.setInputMask(_fromUtf8(""))
        self.nameEdit.setText(_fromUtf8(""))
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.horizontalLayout_2.addWidget(self.nameEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(OwnerTab)
        self.label_3.setMinimumSize(QtCore.QSize(100, 25))
        self.label_3.setMaximumSize(QtCore.QSize(100, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.addressEdit = QtGui.QLineEdit(OwnerTab)
        self.addressEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.addressEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.addressEdit.setObjectName(_fromUtf8("addressEdit"))
        self.horizontalLayout_3.addWidget(self.addressEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(OwnerTab)
        self.label.setMinimumSize(QtCore.QSize(100, 25))
        self.label.setMaximumSize(QtCore.QSize(100, 25))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.postOfficeComboBox = QtGui.QComboBox(OwnerTab)
        self.postOfficeComboBox.setObjectName(_fromUtf8("postOfficeComboBox"))
        self.horizontalLayout.addWidget(self.postOfficeComboBox)
        self.addPostOfficeButton = QtGui.QPushButton(OwnerTab)
        self.addPostOfficeButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addPostOfficeButton.setMaximumSize(QtCore.QSize(25, 25))
        self.addPostOfficeButton.setObjectName(_fromUtf8("addPostOfficeButton"))
        self.horizontalLayout.addWidget(self.addPostOfficeButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(OwnerTab)
        self.label_4.setMinimumSize(QtCore.QSize(100, 25))
        self.label_4.setMaximumSize(QtCore.QSize(100, 25))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.postNumberComboBox = QtGui.QComboBox(OwnerTab)
        self.postNumberComboBox.setObjectName(_fromUtf8("postNumberComboBox"))
        self.horizontalLayout_5.addWidget(self.postNumberComboBox)
        self.addPostNumberButton = QtGui.QPushButton(OwnerTab)
        self.addPostNumberButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addPostNumberButton.setMaximumSize(QtCore.QSize(25, 25))
        self.addPostNumberButton.setObjectName(_fromUtf8("addPostNumberButton"))
        self.horizontalLayout_5.addWidget(self.addPostNumberButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(OwnerTab)
        self.label_6.setMinimumSize(QtCore.QSize(100, 25))
        self.label_6.setMaximumSize(QtCore.QSize(100, 25))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.phonenumberEdit = QtGui.QLineEdit(OwnerTab)
        self.phonenumberEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.phonenumberEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.phonenumberEdit.setObjectName(_fromUtf8("phonenumberEdit"))
        self.horizontalLayout_7.addWidget(self.phonenumberEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(OwnerTab)
        self.label_5.setMinimumSize(QtCore.QSize(100, 25))
        self.label_5.setMaximumSize(QtCore.QSize(100, 25))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.emailEdit = QtGui.QLineEdit(OwnerTab)
        self.emailEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.emailEdit.setMaximumSize(QtCore.QSize(200, 20))
        self.emailEdit.setObjectName(_fromUtf8("emailEdit"))
        self.horizontalLayout_6.addWidget(self.emailEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_7 = QtGui.QLabel(OwnerTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.otherInfoEdit = QtGui.QPlainTextEdit(OwnerTab)
        self.otherInfoEdit.setMaximumSize(QtCore.QSize(306, 200))
        self.otherInfoEdit.setToolTip(_fromUtf8(""))
        self.otherInfoEdit.setObjectName(_fromUtf8("otherInfoEdit"))
        self.verticalLayout_2.addWidget(self.otherInfoEdit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.animalvisitLayout = QtGui.QVBoxLayout()
        self.animalvisitLayout.setObjectName(_fromUtf8("animalvisitLayout"))
        self.horizontalLayout_9.addLayout(self.animalvisitLayout)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.canselButton = QtGui.QPushButton(OwnerTab)
        self.canselButton.setObjectName(_fromUtf8("canselButton"))
        self.horizontalLayout_8.addWidget(self.canselButton)
        self.saveButton = QtGui.QPushButton(OwnerTab)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_8.addWidget(self.saveButton)
        self.saveAndExitButton = QtGui.QPushButton(OwnerTab)
        self.saveAndExitButton.setObjectName(_fromUtf8("saveAndExitButton"))
        self.horizontalLayout_8.addWidget(self.saveAndExitButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.setStretch(0, 1)

        self.retranslateUi(OwnerTab)
        QtCore.QMetaObject.connectSlotsByName(OwnerTab)

    def retranslateUi(self, OwnerTab):
        OwnerTab.setWindowTitle(QtGui.QApplication.translate("OwnerTab", "OwnerTab", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OwnerTab", "Nimi", None, QtGui.QApplication.UnicodeUTF8))
        self.nameEdit.setPlaceholderText(QtGui.QApplication.translate("OwnerTab", "Koko nimi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OwnerTab", "Osoite", None, QtGui.QApplication.UnicodeUTF8))
        self.addressEdit.setPlaceholderText(QtGui.QApplication.translate("OwnerTab", "Osoite", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OwnerTab", "Postitoimipaikka", None, QtGui.QApplication.UnicodeUTF8))
        self.addPostOfficeButton.setToolTip(QtGui.QApplication.translate("OwnerTab", "Lisää postitoimipaikka", None, QtGui.QApplication.UnicodeUTF8))
        self.addPostOfficeButton.setText(QtGui.QApplication.translate("OwnerTab", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OwnerTab", "Postinumero", None, QtGui.QApplication.UnicodeUTF8))
        self.addPostNumberButton.setToolTip(QtGui.QApplication.translate("OwnerTab", "Lisää postinumero", None, QtGui.QApplication.UnicodeUTF8))
        self.addPostNumberButton.setText(QtGui.QApplication.translate("OwnerTab", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("OwnerTab", "Puhelinnumero", None, QtGui.QApplication.UnicodeUTF8))
        self.phonenumberEdit.setPlaceholderText(QtGui.QApplication.translate("OwnerTab", "Puhelinnumero", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OwnerTab", "Sähköposti", None, QtGui.QApplication.UnicodeUTF8))
        self.emailEdit.setPlaceholderText(QtGui.QApplication.translate("OwnerTab", "Sähköposti", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("OwnerTab", "Muut tiedot", None, QtGui.QApplication.UnicodeUTF8))
        self.canselButton.setText(QtGui.QApplication.translate("OwnerTab", "Sulje", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setToolTip(QtGui.QApplication.translate("OwnerTab", "Tallentaa omistajaan tehdyt muutokset", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("OwnerTab", "Tallenna", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAndExitButton.setToolTip(QtGui.QApplication.translate("OwnerTab", "Tallentaa omistajaan tehdyt muutokset ja sulkee välilehden", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAndExitButton.setText(QtGui.QApplication.translate("OwnerTab", "Tallenna ja sulje", None, QtGui.QApplication.UnicodeUTF8))

