# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uipy/ui_visit.ui'
#
# Created: Tue Jun 30 21:56:00 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Visit(object):
    def setupUi(self, Visit):
        Visit.setObjectName(_fromUtf8("Visit"))
        Visit.resize(1117, 786)
        self.verticalLayout_11 = QtGui.QVBoxLayout(Visit)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ownerLayout = QtGui.QHBoxLayout()
        self.ownerLayout.setObjectName(_fromUtf8("ownerLayout"))
        self.owner = QtGui.QLabel(Visit)
        self.owner.setMinimumSize(QtCore.QSize(80, 0))
        self.owner.setObjectName(_fromUtf8("owner"))
        self.ownerLayout.addWidget(self.owner)
        self.verticalLayout.addLayout(self.ownerLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startlabel = QtGui.QLabel(Visit)
        self.startlabel.setMinimumSize(QtCore.QSize(80, 0))
        self.startlabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.startlabel.setObjectName(_fromUtf8("startlabel"))
        self.horizontalLayout.addWidget(self.startlabel)
        self.startTimeEdit = QtGui.QDateTimeEdit(Visit)
        self.startTimeEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.startTimeEdit.setObjectName(_fromUtf8("startTimeEdit"))
        self.horizontalLayout.addWidget(self.startTimeEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.endlabel = QtGui.QLabel(Visit)
        self.endlabel.setMinimumSize(QtCore.QSize(80, 0))
        self.endlabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.endlabel.setObjectName(_fromUtf8("endlabel"))
        self.horizontalLayout_2.addWidget(self.endlabel)
        self.endTimeEdit = QtGui.QDateTimeEdit(Visit)
        self.endTimeEdit.setEnabled(True)
        self.endTimeEdit.setObjectName(_fromUtf8("endTimeEdit"))
        self.horizontalLayout_2.addWidget(self.endTimeEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(Visit)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.vetComboBox = QtGui.QComboBox(Visit)
        self.vetComboBox.setObjectName(_fromUtf8("vetComboBox"))
        self.horizontalLayout_3.addWidget(self.vetComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_10 = QtGui.QLabel(Visit)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.animalNameLabel = QtGui.QLabel(Visit)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.animalNameLabel.setFont(font)
        self.animalNameLabel.setObjectName(_fromUtf8("animalNameLabel"))
        self.verticalLayout_3.addWidget(self.animalNameLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.animalSelectorLayout = QtGui.QHBoxLayout()
        self.animalSelectorLayout.setObjectName(_fromUtf8("animalSelectorLayout"))
        self.verticalLayout_9.addLayout(self.animalSelectorLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.amamnesisLabel = QtGui.QLabel(Visit)
        self.amamnesisLabel.setObjectName(_fromUtf8("amamnesisLabel"))
        self.verticalLayout_8.addWidget(self.amamnesisLabel)
        self.amanuensisTextEdit = QtGui.QPlainTextEdit(Visit)
        self.amanuensisTextEdit.setObjectName(_fromUtf8("amanuensisTextEdit"))
        self.verticalLayout_8.addWidget(self.amanuensisTextEdit)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.statusLabel = QtGui.QLabel(Visit)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.verticalLayout_7.addWidget(self.statusLabel)
        self.statusTextEdit = QtGui.QPlainTextEdit(Visit)
        self.statusTextEdit.setObjectName(_fromUtf8("statusTextEdit"))
        self.verticalLayout_7.addWidget(self.statusTextEdit)
        self.verticalLayout_12.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.diagnosisLabel = QtGui.QLabel(Visit)
        self.diagnosisLabel.setObjectName(_fromUtf8("diagnosisLabel"))
        self.verticalLayout_6.addWidget(self.diagnosisLabel)
        self.diagnosisTextEdit = QtGui.QPlainTextEdit(Visit)
        self.diagnosisTextEdit.setObjectName(_fromUtf8("diagnosisTextEdit"))
        self.verticalLayout_6.addWidget(self.diagnosisTextEdit)
        self.verticalLayout_12.addLayout(self.verticalLayout_6)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.threatmentLabel = QtGui.QLabel(Visit)
        self.threatmentLabel.setObjectName(_fromUtf8("threatmentLabel"))
        self.horizontalLayout_12.addWidget(self.threatmentLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.openSummaryButton = QtGui.QPushButton(Visit)
        self.openSummaryButton.setObjectName(_fromUtf8("openSummaryButton"))
        self.horizontalLayout_12.addWidget(self.openSummaryButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.treatmentTextEdit = QtGui.QPlainTextEdit(Visit)
        self.treatmentTextEdit.setObjectName(_fromUtf8("treatmentTextEdit"))
        self.verticalLayout_10.addWidget(self.treatmentTextEdit)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.itemAddLayout = QtGui.QVBoxLayout()
        self.itemAddLayout.setObjectName(_fromUtf8("itemAddLayout"))
        self.horizontalLayout_4.addLayout(self.itemAddLayout)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.operationMainLayout = QtGui.QHBoxLayout()
        self.operationMainLayout.setObjectName(_fromUtf8("operationMainLayout"))
        self.operationLayout = QtGui.QHBoxLayout()
        self.operationLayout.setObjectName(_fromUtf8("operationLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.operationNameLabel = QtGui.QLabel(Visit)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.operationNameLabel.setFont(font)
        self.operationNameLabel.setObjectName(_fromUtf8("operationNameLabel"))
        self.verticalLayout_5.addWidget(self.operationNameLabel)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.priceLabel = QtGui.QLabel(Visit)
        self.priceLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.priceLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.priceLabel.setObjectName(_fromUtf8("priceLabel"))
        self.horizontalLayout_6.addWidget(self.priceLabel)
        self.priceSpinBox = QtGui.QDoubleSpinBox(Visit)
        self.priceSpinBox.setMaximumSize(QtCore.QSize(106, 16777215))
        self.priceSpinBox.setMaximum(999999999.95)
        self.priceSpinBox.setSingleStep(0.05)
        self.priceSpinBox.setObjectName(_fromUtf8("priceSpinBox"))
        self.horizontalLayout_6.addWidget(self.priceSpinBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.horizontalLayout_6.setStretch(2, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.retailPriceLabel_2 = QtGui.QLabel(Visit)
        self.retailPriceLabel_2.setMinimumSize(QtCore.QSize(83, 0))
        self.retailPriceLabel_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.retailPriceLabel_2.setObjectName(_fromUtf8("retailPriceLabel_2"))
        self.horizontalLayout_7.addWidget(self.retailPriceLabel_2)
        self.retailPriceLabel = QtGui.QLabel(Visit)
        self.retailPriceLabel.setMinimumSize(QtCore.QSize(97, 0))
        self.retailPriceLabel.setFrameShape(QtGui.QFrame.Box)
        self.retailPriceLabel.setObjectName(_fromUtf8("retailPriceLabel"))
        self.horizontalLayout_7.addWidget(self.retailPriceLabel)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.countLabel = QtGui.QLabel(Visit)
        self.countLabel.setMinimumSize(QtCore.QSize(83, 0))
        self.countLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.countLabel.setObjectName(_fromUtf8("countLabel"))
        self.horizontalLayout_10.addWidget(self.countLabel)
        self.countSpinBox = QtGui.QDoubleSpinBox(Visit)
        self.countSpinBox.setMinimumSize(QtCore.QSize(106, 0))
        self.countSpinBox.setMaximumSize(QtCore.QSize(106, 16777215))
        self.countSpinBox.setMinimum(1.0)
        self.countSpinBox.setMaximum(999999.0)
        self.countSpinBox.setSingleStep(1.0)
        self.countSpinBox.setObjectName(_fromUtf8("countSpinBox"))
        self.horizontalLayout_10.addWidget(self.countSpinBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 2)
        self.horizontalLayout_10.setStretch(2, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.descriptionLabel = QtGui.QLabel(Visit)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.verticalLayout_4.addWidget(self.descriptionLabel)
        self.descriptionTextEdit = QtGui.QPlainTextEdit(Visit)
        self.descriptionTextEdit.setObjectName(_fromUtf8("descriptionTextEdit"))
        self.verticalLayout_4.addWidget(self.descriptionTextEdit)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.operationLayout.addLayout(self.verticalLayout_5)
        self.stackedWidget = QtGui.QStackedWidget(Visit)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.emptyPage = QtGui.QWidget()
        self.emptyPage.setObjectName(_fromUtf8("emptyPage"))
        self.stackedWidget.addWidget(self.emptyPage)
        self.ItemInfoPage = QtGui.QWidget()
        self.ItemInfoPage.setObjectName(_fromUtf8("ItemInfoPage"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.ItemInfoPage)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.ItemInfoPage)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.nameLabel = QtGui.QLabel(self.ItemInfoPage)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nameLabel)
        self.label_4 = QtGui.QLabel(self.ItemInfoPage)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.typeLabel = QtGui.QLabel(self.ItemInfoPage)
        self.typeLabel.setObjectName(_fromUtf8("typeLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.typeLabel)
        self.label_5 = QtGui.QLabel(self.ItemInfoPage)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.itemPriceLabel = QtGui.QLabel(self.ItemInfoPage)
        self.itemPriceLabel.setObjectName(_fromUtf8("itemPriceLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.itemPriceLabel)
        self.label_3 = QtGui.QLabel(self.ItemInfoPage)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_9.addLayout(self.formLayout)
        self.stackedWidget.addWidget(self.ItemInfoPage)
        self.treeWidgetPage = QtGui.QWidget()
        self.treeWidgetPage.setObjectName(_fromUtf8("treeWidgetPage"))
        self.itemTreeWidgetLayout = QtGui.QVBoxLayout(self.treeWidgetPage)
        self.itemTreeWidgetLayout.setObjectName(_fromUtf8("itemTreeWidgetLayout"))
        self.stackedWidget.addWidget(self.treeWidgetPage)
        self.operationLayout.addWidget(self.stackedWidget)
        self.operationLayout.setStretch(0, 1)
        self.operationLayout.setStretch(1, 2)
        self.operationMainLayout.addLayout(self.operationLayout)
        self.verticalLayout_11.addLayout(self.operationMainLayout)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.billButton = QtGui.QPushButton(Visit)
        self.billButton.setObjectName(_fromUtf8("billButton"))
        self.horizontalLayout_13.addWidget(self.billButton)
        spacerItem7 = QtGui.QSpacerItem(17, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.closeButton = QtGui.QPushButton(Visit)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_13.addWidget(self.closeButton)
        self.saveButton = QtGui.QPushButton(Visit)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_13.addWidget(self.saveButton)
        self.saveandcloseButton = QtGui.QPushButton(Visit)
        self.saveandcloseButton.setObjectName(_fromUtf8("saveandcloseButton"))
        self.horizontalLayout_13.addWidget(self.saveandcloseButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 5)

        self.retranslateUi(Visit)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Visit)

    def retranslateUi(self, Visit):
        Visit.setWindowTitle(_translate("Visit", "Form", None))
        self.owner.setText(_translate("Visit", "Omistaja", None))
        self.startlabel.setText(_translate("Visit", "Aloitus aika", None))
        self.startTimeEdit.setDisplayFormat(_translate("Visit", "d.M.yyyy H.mm", None))
        self.endlabel.setText(_translate("Visit", "Lopetus aika", None))
        self.label_2.setText(_translate("Visit", "Eläinlääkäri", None))
        self.label_10.setText(_translate("Visit", "Valittu Eläin:", None))
        self.animalNameLabel.setText(_translate("Visit", "Ei valittua eläintä", None))
        self.amamnesisLabel.setText(_translate("Visit", "Anamneesi", None))
        self.statusLabel.setText(_translate("Visit", "Status", None))
        self.diagnosisLabel.setText(_translate("Visit", "Diagnoosi", None))
        self.threatmentLabel.setText(_translate("Visit", "Yhteenveto/Hoito-ohje", None))
        self.openSummaryButton.setText(_translate("Visit", "Avaa", None))
        self.operationNameLabel.setText(_translate("Visit", "Nimi", None))
        self.priceLabel.setText(_translate("Visit", "Hinta", None))
        self.priceSpinBox.setToolTip(_translate("Visit", "Painamalla Ctrl:n pohjaan voit rullata lukuja nopeammin", None))
        self.retailPriceLabel_2.setText(_translate("Visit", "Ohjehinta", None))
        self.retailPriceLabel.setText(_translate("Visit", "0.00", None))
        self.countLabel.setText(_translate("Visit", "Määrä", None))
        self.descriptionLabel.setText(_translate("Visit", "Kuvaus", None))
        self.label.setText(_translate("Visit", "Nimi", None))
        self.nameLabel.setText(_translate("Visit", "Name", None))
        self.label_4.setText(_translate("Visit", "Tyyppi", None))
        self.typeLabel.setText(_translate("Visit", "Type", None))
        self.label_5.setText(_translate("Visit", "Hinta", None))
        self.itemPriceLabel.setText(_translate("Visit", "0.0", None))
        self.label_3.setText(_translate("Visit", "Tuotetiedot", None))
        self.billButton.setText(_translate("Visit", "Lasku", None))
        self.closeButton.setText(_translate("Visit", "Poistu", None))
        self.saveButton.setText(_translate("Visit", "Tallenna", None))
        self.saveandcloseButton.setText(_translate("Visit", "Tallenna ja poistu", None))

