# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_vettab.ui'
#
# Created: Tue Apr 23 11:51:16 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_VetTab(object):
    def setupUi(self, VetTab):
        VetTab.setObjectName(_fromUtf8("VetTab"))
        VetTab.resize(786, 511)
        font = QtGui.QFont()
        font.setUnderline(False)
        VetTab.setFont(font)
        self.verticalLayout_3 = QtGui.QVBoxLayout(VetTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.basicInfoLayout = QtGui.QVBoxLayout()
        self.basicInfoLayout.setObjectName(_fromUtf8("basicInfoLayout"))
        self.label_9 = QtGui.QLabel(VetTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.basicInfoLayout.addWidget(self.label_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(VetTab)
        self.label_10.setMinimumSize(QtCore.QSize(93, 0))
        self.label_10.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.comboBox = QtGui.QComboBox(VetTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_11.addWidget(self.comboBox)
        self.basicInfoLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(VetTab)
        self.label.setMinimumSize(QtCore.QSize(93, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.nameEdit = QtGui.QLineEdit(VetTab)
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.horizontalLayout.addWidget(self.nameEdit)
        self.basicInfoLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(VetTab)
        self.label_2.setMinimumSize(QtCore.QSize(93, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.addressEdit = QtGui.QLineEdit(VetTab)
        self.addressEdit.setObjectName(_fromUtf8("addressEdit"))
        self.horizontalLayout_2.addWidget(self.addressEdit)
        self.basicInfoLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(VetTab)
        self.label_3.setMinimumSize(QtCore.QSize(93, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.postOfficeComboBox = QtGui.QComboBox(VetTab)
        self.postOfficeComboBox.setMinimumSize(QtCore.QSize(140, 0))
        self.postOfficeComboBox.setObjectName(_fromUtf8("postOfficeComboBox"))
        self.horizontalLayout_3.addWidget(self.postOfficeComboBox)
        self.addPostOfficeButton = QtGui.QPushButton(VetTab)
        self.addPostOfficeButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addPostOfficeButton.setMaximumSize(QtCore.QSize(25, 25))
        self.addPostOfficeButton.setObjectName(_fromUtf8("addPostOfficeButton"))
        self.horizontalLayout_3.addWidget(self.addPostOfficeButton)
        self.basicInfoLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(VetTab)
        self.label_4.setMinimumSize(QtCore.QSize(93, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.postNumberComboBox = QtGui.QComboBox(VetTab)
        self.postNumberComboBox.setMinimumSize(QtCore.QSize(140, 0))
        self.postNumberComboBox.setObjectName(_fromUtf8("postNumberComboBox"))
        self.horizontalLayout_4.addWidget(self.postNumberComboBox)
        self.addPostNumberButton = QtGui.QPushButton(VetTab)
        self.addPostNumberButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addPostNumberButton.setMaximumSize(QtCore.QSize(25, 25))
        self.addPostNumberButton.setObjectName(_fromUtf8("addPostNumberButton"))
        self.horizontalLayout_4.addWidget(self.addPostNumberButton)
        self.basicInfoLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(VetTab)
        self.label_5.setMinimumSize(QtCore.QSize(93, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.y_numberEdit = QtGui.QLineEdit(VetTab)
        self.y_numberEdit.setObjectName(_fromUtf8("y_numberEdit"))
        self.horizontalLayout_5.addWidget(self.y_numberEdit)
        self.basicInfoLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(VetTab)
        self.label_6.setMinimumSize(QtCore.QSize(93, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.vetNumberEdit = QtGui.QLineEdit(VetTab)
        self.vetNumberEdit.setObjectName(_fromUtf8("vetNumberEdit"))
        self.horizontalLayout_6.addWidget(self.vetNumberEdit)
        self.basicInfoLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(VetTab)
        self.label_8.setMinimumSize(QtCore.QSize(93, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.bankEdit = QtGui.QLineEdit(VetTab)
        self.bankEdit.setObjectName(_fromUtf8("bankEdit"))
        self.horizontalLayout_8.addWidget(self.bankEdit)
        self.basicInfoLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(VetTab)
        self.label_7.setMinimumSize(QtCore.QSize(93, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.IbanEdit = QtGui.QLineEdit(VetTab)
        self.IbanEdit.setObjectName(_fromUtf8("IbanEdit"))
        self.horizontalLayout_7.addWidget(self.IbanEdit)
        self.basicInfoLayout.addLayout(self.horizontalLayout_7)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.basicInfoLayout.addItem(spacerItem)
        self.horizontalLayout_12.addLayout(self.basicInfoLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_14 = QtGui.QLabel(VetTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_13 = QtGui.QLabel(VetTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.finnishPextEdit = QtGui.QPlainTextEdit(VetTab)
        self.finnishPextEdit.setObjectName(_fromUtf8("finnishPextEdit"))
        self.verticalLayout_2.addWidget(self.finnishPextEdit)
        self.label_12 = QtGui.QLabel(VetTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.swedenTextEdit = QtGui.QPlainTextEdit(VetTab)
        self.swedenTextEdit.setObjectName(_fromUtf8("swedenTextEdit"))
        self.verticalLayout_2.addWidget(self.swedenTextEdit)
        self.label_11 = QtGui.QLabel(VetTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.englishTextEdit_3 = QtGui.QPlainTextEdit(VetTab)
        self.englishTextEdit_3.setObjectName(_fromUtf8("englishTextEdit_3"))
        self.verticalLayout_2.addWidget(self.englishTextEdit_3)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.closeButton = QtGui.QPushButton(VetTab)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_9.addWidget(self.closeButton)
        self.saveButton = QtGui.QPushButton(VetTab)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_9.addWidget(self.saveButton)
        self.saveAndCloseButton = QtGui.QPushButton(VetTab)
        self.saveAndCloseButton.setObjectName(_fromUtf8("saveAndCloseButton"))
        self.horizontalLayout_9.addWidget(self.saveAndCloseButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)

        self.retranslateUi(VetTab)
        QtCore.QMetaObject.connectSlotsByName(VetTab)

    def retranslateUi(self, VetTab):
        VetTab.setWindowTitle(QtGui.QApplication.translate("VetTab", "VetTab", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("VetTab", "Eläinlääkäri", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("VetTab", "Eläinlääkäri", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setToolTip(QtGui.QApplication.translate("VetTab", "Valitse tyhjä luodaksesi uusi", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VetTab", "Nimi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("VetTab", "Osoite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("VetTab", "Postitoimipaikka", None, QtGui.QApplication.UnicodeUTF8))
        self.addPostOfficeButton.setText(QtGui.QApplication.translate("VetTab", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VetTab", "Postinumero", None, QtGui.QApplication.UnicodeUTF8))
        self.addPostNumberButton.setText(QtGui.QApplication.translate("VetTab", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("VetTab", "Y-numero", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("VetTab", "Eläilääkäri nro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("VetTab", "Pankki", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("VetTab", "IBAN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("VetTab", "Asiakas tekstit laskuun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("VetTab", "Suomi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("VetTab", "Ruotsi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("VetTab", "Englanti", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("VetTab", "Sulje", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("VetTab", "Tallenna", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAndCloseButton.setText(QtGui.QApplication.translate("VetTab", "Tallenna ja sulje", None, QtGui.QApplication.UnicodeUTF8))

